[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"

[".config/ghostty/shaders"]
    type = "git-repo"
    url = "https://github.com/m-ahdal/ghostty-shaders"

[".config/btop/themes/catppuccin_mocha.theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/btop/refs/heads/main/themes/catppuccin_mocha.theme"
    refreshPeriod = "168h"
