# https://taskfile.dev

version: "3"


tasks:
  zettel:open:
    dir: ~/workspace/maowen-archive/
    cmds:
      - NVIM_APPNAME="nvim-maowen" nvim ./README.md
  zettel:open:tasks:
    dir: ~/workspace/maowen-archive/
    cmds:
      - NVIM_APPNAME="nvim-maowen" nvim ./TASKS.md
